### ISSUE TITLE
Official Steam API for Pricing

### ISSUE THREAD

**Issue by SLMT** [BrakeValve/dataflow#5]
I found the official API for pricing information from [here](http://stackoverflow.com/questions/13784059/steam-webapi-get-the-price-of-an-app)

First, you can get the list of apps on Steam via this link:

[http://api.steampowered.com/ISteamApps/GetAppList/v0001/](http://api.steampowered.com/ISteamApps/GetAppList/v0001/)

Then, get the information of an app via this API:

```
http://store.steampowered.com/api/appdetails?appids=[App Id]&cc=[Country Code]
```

`[App Id]` is the id of the app on Steam. `[Country Code]` is one of the codes defined in [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1).

For example, you can get the information about "LEGO® STAR WARS™: The Force Awakens" via this link:

[http://store.steampowered.com/api/appdetails?appids=438640&cc=tw](http://store.steampowered.com/api/appdetails?appids=438640&cc=tw)

To get the price information, follow this hierarchy: `[App Id]` > `data` > `price_overview`. Here is an example of `price_overview` from the above link:

```
"price_overview":{
    "currency":"TWD",
    "initial":165000,
    "final":115500,
    "discount_percent":30
}
```

Note that all prices are represented in **cents** (not dollars) with corresponding currency and this field may be omitted if the game is **free-to-play**.

I recommend us to use the official API to collect the data.

**Comment by SLMT** [comment]
I also found that we can add a filter to omit those unnecessary information:

```
http://store.steampowered.com/api/appdetails?appids=[App Id]&cc=[Country Code]&filters=price_overview
```

like this:

[http://store.steampowered.com/api/appdetails?appids=438640&cc=us&filters=price_overview](http://store.steampowered.com/api/appdetails?appids=438640&cc=us&filters=price_overview)

Here is someone's survey about this API:

[https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI#Known_methods](https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI#Known_methods)

**Comment by SLMT** [comment]
There is a way to retrieve the pricing information of multiple applications in a single request. Just add `,` to separate multiple ids:

```
http://store.steampowered.com/api/appdetails?appids=[App Id]{,[App Id]}&cc=[Country Code]&filters=price_overview
```

For example:

[http://store.steampowered.com/api/appdetails?appids=438640,417800&cc=us&filters=price_overview](http://store.steampowered.com/api/appdetails?appids=438640,417800&cc=us&filters=price_overview)

**Comment by ChingTsai** [comment]
Great thanks to SLMT to provide these usufull info.
I will replace the steamDB api in the crawler to this steam offical  api, since SteamDB doesn't encourage us to get price data from them.

**Comment by cyhsutw** [comment]
Great thanks to @SLMT for the input.

@ChingTsai Since there isn't a way to get historical data using the API mentioned above, do you have any idea on how we can get the data we need for prediction?

**Comment by cyhsutw** [comment]
Great thanks to @SLMT for the input.

@ChingTsai Since there isn't a way to get historical data using the API mentioned above, do you have any idea on how we can get the data we need for prediction?

**Comment by ChingTsai** [comment]
@cyhsutw  the only solution is using the API @SLMT provided and start to collect it every day from now on. But for those apps that are not on our collecting list, I think we still can get the initial data from SteamDB and then collect the reset on our own.

**Comment by vulovicv23** [comment]
Hey all!

Is there a way to get other currencies?

Since when executing:
https://store.steampowered.com/api/appdetails?appids=438640,205100&cc=us&filters=price_overview

I get only USD?

Thanks!

**Comment by melihsunbul** [comment]
Hi @vulovicv23, You can change cc parameter to get other currencies. For example en, tr, etc.

**Comment by JoaquinBruhn** [comment]
How could this be used on javascript using fetch() I´m trying to use the json response for a simple site I´m building but the requests is always rejected.
I´m tring with this:

fetch("https://store.steampowered.com/api/appdetails?appids=261550", {
  mode: "no-cors"
}).then((res) => {
  console.log(res);
});

not specifying "no-cors" returns an error and I´ve tried specifying the method as well but it´s still rejected. Don´t know what´s wrong since using the link on the browser gives the proper responce.

**Comment by kaftar007** [comment]
i love you <3 :))))))
